CREATE TABLE VIDEOS
(
  videoId VARCHAR(50) NOT NULL,
  title VARCHAR(50) NOT NULL,
  year INTEGER NOT NULL,
  duration INTEGER NOT NULL
);

CREATE TABLE USERS
(
  employeeId VARCHAR(50) NOT NULL,
  firstName VARCHAR(50) NOT NULL,
  lastName VARCHAR(50) NOT NULL,
  userName VARCHAR(50) NOT NULL,
  password VARCHAR(50) NOT NULL,
  administrator BIT NOT NULL
);
